### ISSUE TITLE
To-do Deliverables

### ISSUE THREAD

**Issue by Kalsifer-7** [unitn-baccala/Documentation#6]
- [ ] elementoMenu => alimento
- [ ] hash e salt
- [ ] syncare i Deliverables
- [x] aggiungere titoli documenti
- [x] approfondire gli indici che ora indicizzano solo le macro categorie
- [x] impostare testo arial su tutti i documenti e controllare che la formattazione sia costante
    - [x] D1

To-do D1:
- [x] aggiungere email di conferma registrazione nel D1 => risolto con rnf-1.2
- [x] aggiungere rnf: l'indirizzo email inserito in fase di registrazione deve essere valido (contenere una chiocciola, nessun carattere non permesso, etc) => risolto con rnf-9
    - [x] sistemare i numeri di tutti gli altri RNF e tutti le loro reference => non necessario perché aggiunto per ultimo
- [x] scrivere che tutti i codici oltre che tutti i link devono esser mono uso oltre che temporanei
    - [x] link => risolto modificando rf-1.2 e rf-3.1
    - [x] codice 2fa (al momento irrisolvibile perché il codice non è nemmeno menzionato)
- [x] spiegazione funzionamento 2fa?
- [x] aggiungere rnf: il sistema non deve permettere l'accesso non autorizzato ai dati => rnf 1.3?
- [x] aggiungere rnf per la durata dei link temporanei di reset pw e registrazione => risolto con rnf-5.3 (24h di validità)
- [x] syncare il d1 con la pianificazione dell'attività dei menù decisa nel D2

To-do D2:
- [x] eccezione 1 della descrizione del rf1 (registrazione) deve linkare rnf5 (sicurezza password) nel D2
- [x] eccezioni 2 e 4 della desc. del rf1 devono diventare rnf
- [x] eccezioni 1 e 2 della desc. del rf1 come sopra
- [x] sistemare numeri rnf dopo l'aggiunta del rnf per la validità dell'indirizzo email
- [x] aggiornare diagrammi casi d'uso
- [x] correggere tutti i link

To-do D3:
- [ ] non esiste alcun metodo o modo per pagare
- [ ] rifare il diagramma delle classi post implementazione
- [ ] non c'é metodo per generare il qr code
- [ ] spiegare meglio la precisazione su i18n con esempi
- [ ] Ci sono parecchi problemi relativi al fatto che non abbiamo ancora idea dell’implementazione di alcune componenti
- [ ] niente sovrapposizione di orari

To-do D4:
- API
    - [ ] registrazione
    - [ ] login (json webtoken)
    - [ ] ottenere elementi menu
    - [ ] aggiungere/modificare/eliminare elementi menu

To-do D5:
- [ ] Sezione organizzazione del progetto definire chi ha fatto cosa. Incarichi
- [ ] conteggio ore
- [ ] difficoltà incontrate
